name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Build extension
      run: npm run build
    
    - name: Create test config
      run: |
        echo '{
          "endpoints": [{
            "name": "test",
            "url": "https://httpbin.org/post",
            "auth_type": "none",
            "timeout": 30
          }]
        }' > test-config.json
    
    - name: Run tests
      run: npm test || true
      continue-on-error: true
    
    - name: Package extension
      run: npm run package
    
    - name: Upload artifact
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: n8n-mcp-connector-dev
        path: n8n-mcp-connector.dxt