name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build extension
      run: |
        echo "Building extension..."
        npm run build
        echo "Contents of dist:"
        ls -la dist/
    
    - name: Package extension
      run: |
        echo "Packaging extension..."
        npm run package
        echo "Checking for .dxt file:"
        ls -la *.dxt
    
    - name: Verify package exists
      run: |
        if [ ! -f "n8n-mcp-connector.dxt" ]; then
          echo "ERROR: n8n-mcp-connector.dxt not found!"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi
        echo "Package size:"
        ls -lh n8n-mcp-connector.dxt
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        files: n8n-mcp-connector.dxt
        body: |
          ## n8n MCP Server Connector v${{ github.event.inputs.version }}
          
          ### Installation
          1. Download `n8n-mcp-connector.dxt` below
          2. Open Claude Desktop
          3. Go to Extensions → Install Extension
          4. Select the downloaded file
          
          ### What's Changed
          See [CHANGELOG.md](https://github.com/shalalalaw/n8n-mcp-connector/blob/main/CHANGELOG.md) for details.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}